name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggers

jobs:
  update-vector-tiles:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget osmium-tool gcc g++ make libsqlite3-dev zlib1g-dev
          wget -O tippecanoe-2.64.0.tar.gz https://github.com/felt/tippecanoe/archive/refs/tags/2.64.0.tar.gz
          tar -xzf tippecanoe-2.64.0.tar.gz
          cd tippecanoe-2.64.0
          sudo make -j
          sudo make install

      - name: Download Bulgarian OSM data
        run: |
          mkdir -p data
          wget -O data/bulgaria-latest.osm.pbf https://download.geofabrik.de/europe/bulgaria-latest.osm.pbf
      
      - name: Convert OSM to GeoJSON
        run: |
          osmium export data/bulgaria-latest.osm.pbf -o data/bulgaria-latest.geojson

      - name: Convert GeoJSON to PMTiles
        run: |
          tippecanoe -zg -o data/bulgaria-latest.pmtiles --drop-densest-as-needed data/bulgaria-latest.geojson

      - name: Move PMTiles to static folder
        run: |
          mkdir -p static/tiles
          mv data/bulgaria-latest.pmtiles static/tiles/

      - name: Check if PMTiles has changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data
          git add static/tiles/bulgaria-latest.pmtiles
          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
            exit 0
          else
            echo "Changes detected. Committing."
          fi
  
      - name: Commit and push if changes exist
        if: success()
        run: |
          git commit -m "Daily update: Add latest data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
